### ISSUE TITLE
Fix bug with Datasette 0.45 and ASGI lifespan

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-search-all#8]
_Originally posted by @simonw in https://github.com/dogsheep/github-to-sqlite/issues/41#issuecomment-653962708_

**Comment by simonw** [comment]
Yup that's a bug:
```
% datasette .
INFO:     Started server process [733]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/datasette-search-all-2uhSNKR0/lib/python3.7/site-packages/uvicorn/lifespan/on.py", line 48, in main
    await app(scope, self.receive, self.send)
  File "/Users/simon/.local/share/virtualenvs/datasette-search-all-2uhSNKR0/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/simon/Dropbox/Development/datasette-search-all/datasette_search_all/__init__.py", line 22, in wrapped_app
    path = scope["path"]
KeyError: 'path'
ERROR:    Application startup failed. Exiting.
```
Root cause is https://github.com/simonw/datasette/commit/16f592247a2a0e140ada487e9972645406dcae69

**Comment by simonw** [comment]
Cleanest fix is to switch to using the `register_routes` plugin hook.
